name: wair_d_rec
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - pip=22.3.1
  - python=3.10.9
  - conda-lock=1.4.0
  - hydra-core=1.2.0
  - pytorch-lightning=1.8.1
  - scikit-image=0.19.2
  - pytorch=1.13.1
  - torchvision=0.14.1
  - lightning-bolts=0.6.0
  - pandas=1.5.3
  - tqdm=4.64.1
  - python-dotenv=1.0.0
  - transformers=4.33.0
  - tabulate=0.9.0
  - mmsegmentation=1.0.0
  - mmcv=2.0.0
  - pip:
      - scipy==1.9.3
      - aim==3.18.1